.*: Assembler messages:
.*: Error: improper beqi/bnei immediate value \(-2\)
.*: Error: improper beqi/bnei immediate value \(32\)
.*: Error: improper beqi/bnei immediate value \(34\)
.*: Error: improper beqi/bnei immediate value \(0\)
.*: Error: improper beqi/bnei immediate value \(-3\)
.*: Error: improper beqi/bnei immediate value \(32\)
.*: Error: improper beqi/bnei immediate value \(33\)
.*: Error: improper beqi/bnei immediate value \(0\)
